-- AlterTable
ALTER TABLE "UserPreferences" ADD COLUMN     "afterSyncBackupDatabase" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "afterSyncRefreshMetadata" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "afterSyncSearchMissing" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "alwaysPreviewBeforeSync" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "conflictResolution" TEXT NOT NULL DEFAULT 'skip',
ADD COLUMN     "enableSmartDuplicateDetection" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "fuzzyMatchThreshold" INTEGER NOT NULL DEFAULT 85,
ADD COLUMN     "ignoreCompletedSeries" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "keepSyncHistory" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "maxHistoryEntries" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "monitorOnlyCurrentSeason" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "onlyMainSeries" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "prioritizeAiring" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "scoreBasedMonitoringEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "scoreHighThreshold" INTEGER NOT NULL DEFAULT 8,
ADD COLUMN     "scoreMedThreshold" INTEGER NOT NULL DEFAULT 6,
ADD COLUMN     "skipMovies" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "skipOVAs" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "skipSpecials" BOOLEAN NOT NULL DEFAULT false;
